### PR TITLE
Updated code.

### PR DESCRIPTION
**Pull request by zimage**
- added unit tests for CKey
- added get_secret() and get_compressed() methods to CKey
- added constant to base58.py for private keys (wallet import format)

### CODE REVIEW

**Comment by jgarzik** [comment]
Overall impression: positive, would like to merge, have questions.

**Comment by zimage** [comment]
oops. forgot to mention that in my commit. python3 doesn't have encode/decode, but does have hexilify. This change bled over from my debugging libssl problems on my mac. I thought python3 might make the get_secret code and generate(secret=) code work instead of segfaulting. It works on my linux box, though.

**Comment by ghost** [comment]
Any update on this PR? BIP38 is really important...

**Comment by ghost** [comment]
Why did you close this pr?

**Comment by zimage** [comment]
My git skills are lacking. I was having a hard time merging the upstream changes into my fork, so I made a new fork from jgarzik's master and am merging in my changes.  It's been 6 months since I did any bitcoin crypto code, so the finishing touches have been pretty slow-going. I have the non-EC-Multiply encrypt/decrypt working, and EC-multiply make-intermediate and decrypt are done. I'm still hunting down why my EC-Multiply encrypt isn't correct. Then I'll have to add the confirmation code generation.

**Comment by ghost** [comment]
OK that's good to know another PR is coming. Just FYI @jgarzik is waiting on some pythonize stuff from @petertodd - if you need any help (with git) for example, give me a shout, and many thanks for working on this important addition to the bitcoin library.

**Pull request closed without merging**
