### PR TITLE
Pythonize scripts

### PR DESCRIPTION
**Pull request by petertodd**
Fun stuff like script = CScript() + OP_HASH160 + scripthash + OP_EQUAL is now possible.

Also includes unit-tests for EvalScript(), although plenty of them currently fail.

### CODE REVIEW

**Comment by petertodd** [comment]
BTW to be clear I don't intend this to be merged instantly - I just want to give people an idea of the flavor of API I'm looking at.

**Comment by ghost** [comment]
You should finish up the PR....

**Comment by jgarzik** [comment]
Yah, I've been poking @petertodd on this.  Other PRs (what little there are) are waiting on the pythonize work.

**Comment by petertodd** [comment]
Sorry, I'll try to look at this more later this week, especially re: the goal of getting pynode working. (even if it's working via some hacks)

**Comment by ghost** [comment]
ping @petertodd

**Comment by petertodd** [comment]
@drak Sorry, I'm swamped with paid work until at least the end of the year.

If you wanna help update pynode and finish off pythonize I'd be happy to answer any questions you have though.

**Comment by ghost** [comment]
Sadly I don't know python well enough... :(

**Pull request closed without merging**
